name: Firebase Deployment

on:
  push:
    branches:
      - main  # Change this to the branch you want to trigger the workflow

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Use Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '16'

      - name: Install dependencies
        run: npm install

      - name: Build project
        run: npm run build

      - name: Select Firebase project
        run: |
          npm install -g firebase-tools
          firebase use --token ${{ secrets.FIREBASE_TOKEN }} sema-frontend
      - name: Deploy to Firebase
        run: |
          firebase deploy --token ${{ secrets.FIREBASE_TOKEN }}