name: Firebase Deployment

on:
  push:
    branches:
      - main  # Change this to the branch you want to trigger the workflow

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Use Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '16'

      - name: Install dependencies
        run: npm install

      - name: Build project
        run: npm run build

      - name: Set up Cloud SDK
        uses: google-github-actions/setup-gcloud@v0
        
      - id: 'auth'
        name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v0
        with: 
          credentials_json: '${{ secrets.FIREBASE_TOKEN }}'

      - name: Select Firebase project
        run: |
          npm install -g firebase-tools
          firebase use sema-frontend
      - name: Deploy to Firebase
        run: |
          firebase deploy --token ${{ secrets.FIREBASE_TOKEN }}