name: Firebase Deployment

on:
  push:
    branches:
      - main  # Change this to the branch you want to trigger the workflow

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Use Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 16

      - name: Install dependencies
        run: npm i

      - name: Build project
        run: npm run build

      - name: Deploy to Firebase
        run: |
          npm install -g firebase-tools
          echo $FIREBASE_TOKEN > firebase_token.json
          firebase use sema-frontend
          firebase deploy --token "$(cat firebase_token.json)"
